name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          cache: "npm"

      - name: Install & Build
        run: |
          npm ci --legacy-peer-deps
          npm run test:coverage
          npm run build

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

      - name: Run Lighthouse Audit against Production URL
        run: npx lhci autorun
        env:
          LHCI_URL: https://booktivate.vdovareize.me/
